### ISSUE TITLE
asan fails to unwind from memcmp

### ISSUE THREAD

**Issue by ramosian-glider** [ramosian-glider/sanitizers#47]
Originally reported on Google Code with ID 46

```
clang -faddress-sanitizer    output_tests/memcmp_test.cc && ./a.out  2>&1 | ./scripts/asan_symbolize.py
/

READ of size 1 at 0x7fffb2721024 thread T0
    #0 0x407fcd in memcmp _asan_rtl_
    #1 0x402140 in _start ??:0

The second frame should be main(). 

I guess this is because asan-rt is built w/o frame pointers.
I wonder if we can fix it w/o using frame pointers. 
```

Reported by `konstantin.s.serebryany` on 2012-03-13 01:12:40

**Comment by ramosian-glider** [comment]
```
I thought -funwind-tables is enough. Do you have the .eh_frame section in your binary?

BTW any reason for us not to use frame pointers? The overhead is minor, especially
compared to debugging benefits.
```

Reported by `ramosian.glider` on 2012-03-13 07:54:20

**Comment by ramosian-glider** [comment]
```
I thought we use fast unwind on linux, why do we need unwind tables?
```

Reported by `eugenis@google.com` on 2012-03-13 08:30:51

**Comment by ramosian-glider** [comment]
```
Ah, your're right. Unwind tables are used for exceptions, so we still need them, but
they have nothing to do with stack unwinding in the runtime.
```

Reported by `ramosian.glider` on 2012-03-13 09:02:58

**Comment by ramosian-glider** [comment]
```
Should be fixed by r152768.
We don't need nor want frame pointers in asan-rt. 
```

Reported by `konstantin.s.serebryany` on 2012-03-15 01:41:39
- **Status changed**: `Fixed`

**Comment by ramosian-glider** [comment]
```
Adding Project:AddressSanitizer as part of GitHub migration.
```

Reported by `ramosian.glider` on 2015-07-30 09:12:58
- **Labels added**: ProjectAddressSanitizer
